### ISSUE TITLE
DB opening error regression

### ISSUE THREAD

**Issue by rnewman** [mozilla/datomish#122]
https://github.com/mozilla/datomish-user-agent-service/issues/29

is caused by — bafflingly — updating ClojureScript.

```
-  :dependencies [[org.clojure/clojurescript "1.9.229"]
+  :dependencies [[org.clojure/clojurescript "1.9.293"]
```

in 327711b.

This makes `npm run test` report the same error:

```
Opening /tmp/testing1480374611259.db
Failure: Error: Invalid value for attribute 1, expected :db.type/keyword but got 29
    at Error (native)
    at new $cljs$core$ExceptionInfo$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:11158:19)
    at $cljs$core$ex_info$cljs$0core$0IFn$0_invoke$0arity$02$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:11184:10)
    at $datomish$schema$ensure_valid_value$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:18798:13)
    at /Users/rnewman/moz/git/datomish/target/release-node/datomish.js:30442:388
    at $db$$131$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:30365:55)
    at $c__43885__auto___59290$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:30395:37)
    at $cljs$core$async$impl$ioc_helpers$run_state_machine_wrapped$$ (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:11902:27)
    at /Users/rnewman/moz/git/datomish/target/release-node/datomish.js:30452:14
    at Immediate.$cljs$core$async$impl$dispatch$process_messages$$ [as _onImmediate] (/Users/rnewman/moz/git/datomish/target/release-node/datomish.js:11623:135)
```

**Comment by rnewman** [comment]
I (temporarily?) rolled back to ClojureScript 1.9.229. I suspect that there is a real bug in our code here — at least, I hope there is, otherwise I'm worried about ClojureScript! — so I'll continue to look into it.
