### ISSUE TITLE
Error running npm tests

### ISSUE THREAD

**Issue by jsantell** [mozilla/datomish#123]
Using node 6.3.1 and the following steps, I get an error on npm test on a fresh repo:

```
$ npm install
$ lein cljsbuild once release-node
$ npm test
```

The test doesn't start and I get:

```
> datomish@0.3.3 test /Users/jsantell/Dev/datomish
> babel-node test/js/tests.js

/Users/jsantell/Dev/datomish/target/release-node/datomish.js:51
        ;return this.datomish.js;
                             ^

TypeError: Cannot read property 'js' of undefined
    at Object.<anonymous> (/Users/jsantell/Dev/datomish/target/release-node/datomish.js:51:30)
    at /Users/jsantell/Dev/datomish/target/release-node/datomish.js:53:7
    at /Users/jsantell/Dev/datomish/target/release-node/datomish.js:25:26
    at Object.<anonymous> (/Users/jsantell/Dev/datomish/target/release-node/datomish.js:35:3)
    at Module._compile (module.js:541:32)
    at loader (/Users/jsantell/Dev/datomish/node_modules/babel-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jsantell/Dev/datomish/node_modules/babel-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
npm ERR! Test failed.  See above for more details.
```

Could be something silly I missed, most likely!

**Comment by rnewman** [comment]
Tests should currently be failing for #122, but that's not this.

Does it work if you run `npm run test` rather than `npm test`?

If `npm run test` fails, does it work with Node 6.2.2?

**Comment by jsantell** [comment]
`npm test` and `npm run test` have the same result -- same with running node 6.2.2!

**Comment by rnewman** [comment]
I ran:

```
git clone ~/moz/git/datomish
cd datomish
git co master
lein cljsbuild once release-node
npm install
```

then:

```
$ npm run test
> datomish@0.3.5 test /private/tmp/x/datomish
> babel-node test/js/tests.js

Opening /tmp/testing1480390440885.db
Transaction returned {"tempids":{"#datomish.db.TempId{:part :db.part/user, :idx -1000009}":65539},"added-idents":{},"added-attributes":{},"tx":268435459,"txInstant":1480390441729}
Transaction instant: 1480390441729
Known URLs: ["https://mozilla.org/"]
Most recent visit: 1480390441834
Persistent IDs are 65542, 65541.
Recently visited: [["http://reddit.com/",1480390442184],["https://longreads.com/",1480390442084]]
Done.
```

How big is `target/release-node/datomish.bare.js`?

Could you try blowing away `target/release-node`, then re-run `lein cljsbuild once release-node`?

**Comment by rnewman** [comment]
```
at /Users/jsantell/Dev/datomish/target/release-node/datomish.js:53:7
```

implies that `datomish.bare.js` is empty — `datomish.js` should be about 50,000 lines long, with the dereference in question at the end!

**Comment by jsantell** [comment]
`datomish.bare.js` just contained a polyfill for `Math.imul`. Deleting `target/release-node/` didn't work either, but noticed this during the build:

```
$ lein cljsbuild once release-node
Compiling ClojureScript...
Compiling "target/release-node/datomish.bare.js" from ["src/common" "src/node"]...
WARNING: <resolve-id-literals at line 564 is being replaced at line 564 src/common/datomish/transact.cljc
WARNING: start-transactor at line 830 is being replaced at line 830 src/common/datomish/transact.cljc
Nov 28, 2016 8:37:49 PM com.google.javascript.jscomp.LoggerErrorManager println
SEVERE: /Users/jsantell/Dev/datomish/target/release-node/datomish/transact.js:5518: ERROR - Parse error. primary expression expected
));
 ^

Nov 28, 2016 8:37:49 PM com.google.javascript.jscomp.LoggerErrorManager printSummary
WARNING: 1 error(s), 0 warning(s)
ERROR: JSC_PARSE_ERROR. Parse error. primary expression expected at /Users/jsantell/Dev/datomish/target/release-node/datomish/transact.js line 5518 : 1
Packed target/release-node/datomish.js
Successfully compiled "target/release-node/datomish.bare.js" in 21.047 seconds.
```

Anyways, after blowing out the repo and trying again, I got a build that worked -- not sure how to recreate what I did before... anyways, closing, I'll take better notes next time!
